Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import plotly.express as px

dados_carros = pd.read_table("./dados/CarData.txt", sep="\s+")

colunas_linhas_paralelas = [
    coluna for coluna in dados_carros.columns if coluna not in ["C", "Model"]
]

fig = px.parallel_coordinates(
    dados_carros,
    color="C",
    dimensions=colunas_linhas_paralelas,
    #color_continuous_scale=px.colors.diverging.RdYlBu,
)

fig.write_image("./imagens/trabalho1_q9.png")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mexpress[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpx[39;00m
[1;32m      3[0m dados_carros [38;5;241m=[39m pd[38;5;241m.[39mread_table([38;5;124m"[39m[38;5;124m./dados/CarData.txt[39m[38;5;124m"[39m, sep[38;5;241m=[39m[38;5;124m"[39m[38;5;124m\[39m[38;5;124ms+[39m[38;5;124m"[39m)
[1;32m      5[0m colunas_linhas_paralelas [38;5;241m=[39m [
[1;32m      6[0m     coluna [38;5;28;01mfor[39;00m coluna [38;5;129;01min[39;00m dados_carros[38;5;241m.[39mcolumns [38;5;28;01mif[39;00m coluna [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m [[38;5;124m"[39m[38;5;124mC[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mModel[39m[38;5;124m"[39m]
[1;32m      7[0m ]

[0;31mModuleNotFoundError[0m: No module named 'plotly'
ModuleNotFoundError: No module named 'plotly'

